name: CD - Deploy to EC2 (Ansible)

on:
  workflow_run:
    workflows: ["CI - Test, Build & Push Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout repository so runner can access ansible folder
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2ï¸âƒ£ Install Ansible on GitHub runner
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # 3ï¸âƒ£ Create SSH key file for Ansible
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/devops-key.pem
          chmod 600 ~/.ssh/devops-key.pem

      # 4ï¸âƒ£ Add EC2 host to known_hosts (avoid SSH prompt)
      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 5ï¸âƒ£ Run Ansible Playbook ğŸš€
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
