name: CD - Deploy to EC2 (Ansible)

on:
  workflow_run:
    workflows: ["CI - Test, Build & Push Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout repo so runner can access ansible folder
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Install Ansible on GitHub runner
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # 3Ô∏è‚É£ Setup SSH key for Ansible to connect EC2
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 4Ô∏è‚É£ Run Ansible Playbook üöÄ
      - name: Run Ansible Playbook
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
