name: CI - Test, Build & Push Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install deps
      - name: Install dependencies
        run: npm ci

      # Prisma client
      - name: Generate Prisma Client
        run: npm run prisma:generate

      # Unit tests
      - name: Run unit tests
        run: npm test

      # Integration test using docker compose
      - name: Run Docker Compose integration test
        run: |
          docker compose up -d --build
          sleep 20
          docker compose ps
          docker compose down

      # ğŸ” Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ğŸ³ Build image
      - name: Build Docker image
        run: docker build -t naimeshpatel5295/devnotes:latest .

      # ğŸš€ Push image
      - name: Push Docker image
        run: docker push naimeshpatel5295/devnotes:latest
