name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  # ===============================
  # CI JOB â€” TEST + BUILD + PUSH
  # ===============================
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: Run unit tests
        run: npm test

      - name: Run Docker Compose integration test
        run: npm run compose:test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t naimeshpatel5295/devnotes-app:latest .

      - name: Push Docker image
        run: docker push naimeshpatel5295/devnotes-app:latest


  # ===============================
  # CD JOB â€” AUTO DEPLOY TO EC2
  # ===============================
  deploy:
    needs: test-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "ðŸš€ Starting deployment..."

            # Pull latest image from Docker Hub
            docker pull naimeshpatel5295/devnotes-app:latest

            # Stop and remove old container if exists
            docker stop devnotes-app || true
            docker rm devnotes-app || true

            # Run new container
            docker run -d \
              --name devnotes-app \
              -p 5000:5000 \
              -e PORT=5000 \
              -e DATABASE_URL=postgresql://postgres:password@172.17.0.1:5432/devnotes \
              naimeshpatel5295/devnotes-app:latest

            echo "âœ… Deployment completed!"
